# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ast_parser_pb2 as ast__parser__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ast_parser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ASTParserStub(object):
    """AST 解析服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseFile = channel.unary_unary(
                '/codeaudit.ASTParser/ParseFile',
                request_serializer=ast__parser__pb2.ParseRequest.SerializeToString,
                response_deserializer=ast__parser__pb2.ParseResponse.FromString,
                _registered_method=True)
        self.ParseBatch = channel.unary_stream(
                '/codeaudit.ASTParser/ParseBatch',
                request_serializer=ast__parser__pb2.BatchParseRequest.SerializeToString,
                response_deserializer=ast__parser__pb2.ParseResponse.FromString,
                _registered_method=True)


class ASTParserServicer(object):
    """AST 解析服务
    """

    def ParseFile(self, request, context):
        """解析单个文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseBatch(self, request, context):
        """批量解析文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASTParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseFile,
                    request_deserializer=ast__parser__pb2.ParseRequest.FromString,
                    response_serializer=ast__parser__pb2.ParseResponse.SerializeToString,
            ),
            'ParseBatch': grpc.unary_stream_rpc_method_handler(
                    servicer.ParseBatch,
                    request_deserializer=ast__parser__pb2.BatchParseRequest.FromString,
                    response_serializer=ast__parser__pb2.ParseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codeaudit.ASTParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codeaudit.ASTParser', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ASTParser(object):
    """AST 解析服务
    """

    @staticmethod
    def ParseFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codeaudit.ASTParser/ParseFile',
            ast__parser__pb2.ParseRequest.SerializeToString,
            ast__parser__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/codeaudit.ASTParser/ParseBatch',
            ast__parser__pb2.BatchParseRequest.SerializeToString,
            ast__parser__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
