// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: indexer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 构建索引请求
type BuildIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // 文件路径
	AstData       []byte                 `protobuf:"bytes,2,opt,name=ast_data,json=astData,proto3" json:"ast_data,omitempty"`    // AST数据
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`                 // 编程语言
	Incremental   bool                   `protobuf:"varint,4,opt,name=incremental,proto3" json:"incremental,omitempty"`          // 是否增量索引
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildIndexRequest) Reset() {
	*x = BuildIndexRequest{}
	mi := &file_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildIndexRequest) ProtoMessage() {}

func (x *BuildIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildIndexRequest.ProtoReflect.Descriptor instead.
func (*BuildIndexRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *BuildIndexRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *BuildIndexRequest) GetAstData() []byte {
	if x != nil {
		return x.AstData
	}
	return nil
}

func (x *BuildIndexRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *BuildIndexRequest) GetIncremental() bool {
	if x != nil {
		return x.Incremental
	}
	return false
}

// 构建索引响应
type BuildIndexResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                           // 是否成功
	IndexId          string                 `protobuf:"bytes,2,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`                             // 索引ID
	FunctionsIndexed int32                  `protobuf:"varint,3,opt,name=functions_indexed,json=functionsIndexed,proto3" json:"functions_indexed,omitempty"` // 索引的函数数
	ClassesIndexed   int32                  `protobuf:"varint,4,opt,name=classes_indexed,json=classesIndexed,proto3" json:"classes_indexed,omitempty"`       // 索引的类数
	VariablesIndexed int32                  `protobuf:"varint,5,opt,name=variables_indexed,json=variablesIndexed,proto3" json:"variables_indexed,omitempty"` // 索引的变量数
	ErrorMessage     string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`              // 错误信息
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BuildIndexResponse) Reset() {
	*x = BuildIndexResponse{}
	mi := &file_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildIndexResponse) ProtoMessage() {}

func (x *BuildIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildIndexResponse.ProtoReflect.Descriptor instead.
func (*BuildIndexResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *BuildIndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildIndexResponse) GetIndexId() string {
	if x != nil {
		return x.IndexId
	}
	return ""
}

func (x *BuildIndexResponse) GetFunctionsIndexed() int32 {
	if x != nil {
		return x.FunctionsIndexed
	}
	return 0
}

func (x *BuildIndexResponse) GetClassesIndexed() int32 {
	if x != nil {
		return x.ClassesIndexed
	}
	return 0
}

func (x *BuildIndexResponse) GetVariablesIndexed() int32 {
	if x != nil {
		return x.VariablesIndexed
	}
	return 0
}

func (x *BuildIndexResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 查询函数请求
type QueryFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"` // 函数名称
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`             // 可选：文件路径限制
	ExactMatch    bool                   `protobuf:"varint,3,opt,name=exact_match,json=exactMatch,proto3" json:"exact_match,omitempty"`      // 是否精确匹配
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFunctionRequest) Reset() {
	*x = QueryFunctionRequest{}
	mi := &file_indexer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFunctionRequest) ProtoMessage() {}

func (x *QueryFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFunctionRequest.ProtoReflect.Descriptor instead.
func (*QueryFunctionRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{2}
}

func (x *QueryFunctionRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *QueryFunctionRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *QueryFunctionRequest) GetExactMatch() bool {
	if x != nil {
		return x.ExactMatch
	}
	return false
}

// 函数信息
type FunctionInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                  // 函数ID
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                              // 函数名称
	FilePath             string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                                      // 文件路径
	StartLine            int32                  `protobuf:"varint,4,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`                                  // 起始行号
	EndLine              int32                  `protobuf:"varint,5,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`                                        // 结束行号
	Signature            string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                                                    // 函数签名
	CyclomaticComplexity int32                  `protobuf:"varint,7,opt,name=cyclomatic_complexity,json=cyclomaticComplexity,proto3" json:"cyclomatic_complexity,omitempty"` // 圈复杂度
	Parameters           []string               `protobuf:"bytes,8,rep,name=parameters,proto3" json:"parameters,omitempty"`                                                  // 参数列表
	ReturnType           string                 `protobuf:"bytes,9,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`                                // 返回类型
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FunctionInfo) Reset() {
	*x = FunctionInfo{}
	mi := &file_indexer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInfo) ProtoMessage() {}

func (x *FunctionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInfo.ProtoReflect.Descriptor instead.
func (*FunctionInfo) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{3}
}

func (x *FunctionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FunctionInfo) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *FunctionInfo) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *FunctionInfo) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *FunctionInfo) GetCyclomaticComplexity() int32 {
	if x != nil {
		return x.CyclomaticComplexity
	}
	return 0
}

func (x *FunctionInfo) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *FunctionInfo) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

// 查询函数响应
type QueryFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []*FunctionInfo        `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`                      // 查询结果
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFunctionResponse) Reset() {
	*x = QueryFunctionResponse{}
	mi := &file_indexer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFunctionResponse) ProtoMessage() {}

func (x *QueryFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFunctionResponse.ProtoReflect.Descriptor instead.
func (*QueryFunctionResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{4}
}

func (x *QueryFunctionResponse) GetFunctions() []*FunctionInfo {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *QueryFunctionResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 查询类请求
type QueryClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`     // 类名
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`        // 可选：文件路径限制
	ExactMatch    bool                   `protobuf:"varint,3,opt,name=exact_match,json=exactMatch,proto3" json:"exact_match,omitempty"` // 是否精确匹配
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClassRequest) Reset() {
	*x = QueryClassRequest{}
	mi := &file_indexer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClassRequest) ProtoMessage() {}

func (x *QueryClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClassRequest.ProtoReflect.Descriptor instead.
func (*QueryClassRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{5}
}

func (x *QueryClassRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *QueryClassRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *QueryClassRequest) GetExactMatch() bool {
	if x != nil {
		return x.ExactMatch
	}
	return false
}

// 类信息
type ClassInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // 类ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // 类名
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`     // 文件路径
	StartLine     int32                  `protobuf:"varint,4,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"` // 起始行号
	EndLine       int32                  `protobuf:"varint,5,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`       // 结束行号
	BaseClass     string                 `protobuf:"bytes,6,opt,name=base_class,json=baseClass,proto3" json:"base_class,omitempty"`  // 基类
	Interfaces    []string               `protobuf:"bytes,7,rep,name=interfaces,proto3" json:"interfaces,omitempty"`                 // 实现的接口
	Methods       []*MethodInfo          `protobuf:"bytes,8,rep,name=methods,proto3" json:"methods,omitempty"`                       // 方法列表
	Fields        []string               `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty"`                         // 字段列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassInfo) Reset() {
	*x = ClassInfo{}
	mi := &file_indexer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassInfo) ProtoMessage() {}

func (x *ClassInfo) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassInfo.ProtoReflect.Descriptor instead.
func (*ClassInfo) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{6}
}

func (x *ClassInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClassInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ClassInfo) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *ClassInfo) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *ClassInfo) GetBaseClass() string {
	if x != nil {
		return x.BaseClass
	}
	return ""
}

func (x *ClassInfo) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *ClassInfo) GetMethods() []*MethodInfo {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *ClassInfo) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 方法信息
type MethodInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 方法ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 方法名
	IsStatic      bool                   `protobuf:"varint,3,opt,name=is_static,json=isStatic,proto3" json:"is_static,omitempty"`      // 是否静态
	IsPrivate     bool                   `protobuf:"varint,4,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`   // 是否私有
	ReturnType    string                 `protobuf:"bytes,5,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"` // 返回类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodInfo) Reset() {
	*x = MethodInfo{}
	mi := &file_indexer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodInfo) ProtoMessage() {}

func (x *MethodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodInfo.ProtoReflect.Descriptor instead.
func (*MethodInfo) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{7}
}

func (x *MethodInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MethodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodInfo) GetIsStatic() bool {
	if x != nil {
		return x.IsStatic
	}
	return false
}

func (x *MethodInfo) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *MethodInfo) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

// 查询类响应
type QueryClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classes       []*ClassInfo           `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`                          // 查询结果
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClassResponse) Reset() {
	*x = QueryClassResponse{}
	mi := &file_indexer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClassResponse) ProtoMessage() {}

func (x *QueryClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClassResponse.ProtoReflect.Descriptor instead.
func (*QueryClassResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{8}
}

func (x *QueryClassResponse) GetClasses() []*ClassInfo {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *QueryClassResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 查询调用者请求
type QueryCallersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"` // 目标函数ID
	MaxDepth      int32                  `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`      // 最大深度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCallersRequest) Reset() {
	*x = QueryCallersRequest{}
	mi := &file_indexer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCallersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCallersRequest) ProtoMessage() {}

func (x *QueryCallersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCallersRequest.ProtoReflect.Descriptor instead.
func (*QueryCallersRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{9}
}

func (x *QueryCallersRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *QueryCallersRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

// 查询调用者响应
type QueryCallersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Callers       []*CallInfo            `protobuf:"bytes,1,rep,name=callers,proto3" json:"callers,omitempty"`                          // 调用者列表
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCallersResponse) Reset() {
	*x = QueryCallersResponse{}
	mi := &file_indexer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCallersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCallersResponse) ProtoMessage() {}

func (x *QueryCallersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCallersResponse.ProtoReflect.Descriptor instead.
func (*QueryCallersResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{10}
}

func (x *QueryCallersResponse) GetCallers() []*CallInfo {
	if x != nil {
		return x.Callers
	}
	return nil
}

func (x *QueryCallersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 调用信息
type CallInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerId      string                 `protobuf:"bytes,1,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`       // 调用者ID
	CallerName    string                 `protobuf:"bytes,2,opt,name=caller_name,json=callerName,proto3" json:"caller_name,omitempty"` // 调用者名称
	CalleeId      string                 `protobuf:"bytes,3,opt,name=callee_id,json=calleeId,proto3" json:"callee_id,omitempty"`       // 被调用者ID
	CalleeName    string                 `protobuf:"bytes,4,opt,name=callee_name,json=calleeName,proto3" json:"callee_name,omitempty"` // 被调用者名称
	CallLine      int32                  `protobuf:"varint,5,opt,name=call_line,json=callLine,proto3" json:"call_line,omitempty"`      // 调用行号
	CallType      string                 `protobuf:"bytes,6,opt,name=call_type,json=callType,proto3" json:"call_type,omitempty"`       // 调用类型（direct, indirect）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallInfo) Reset() {
	*x = CallInfo{}
	mi := &file_indexer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallInfo) ProtoMessage() {}

func (x *CallInfo) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallInfo.ProtoReflect.Descriptor instead.
func (*CallInfo) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{11}
}

func (x *CallInfo) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *CallInfo) GetCallerName() string {
	if x != nil {
		return x.CallerName
	}
	return ""
}

func (x *CallInfo) GetCalleeId() string {
	if x != nil {
		return x.CalleeId
	}
	return ""
}

func (x *CallInfo) GetCalleeName() string {
	if x != nil {
		return x.CalleeName
	}
	return ""
}

func (x *CallInfo) GetCallLine() int32 {
	if x != nil {
		return x.CallLine
	}
	return 0
}

func (x *CallInfo) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

// 查询被调用者请求
type QueryCalleesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionId    string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"` // 源函数ID
	MaxDepth      int32                  `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`      // 最大深度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCalleesRequest) Reset() {
	*x = QueryCalleesRequest{}
	mi := &file_indexer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCalleesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCalleesRequest) ProtoMessage() {}

func (x *QueryCalleesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCalleesRequest.ProtoReflect.Descriptor instead.
func (*QueryCalleesRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{12}
}

func (x *QueryCalleesRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *QueryCalleesRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

// 查询被调用者响应
type QueryCalleesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Callees       []*CallInfo            `protobuf:"bytes,1,rep,name=callees,proto3" json:"callees,omitempty"`                          // 被调用者列表
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCalleesResponse) Reset() {
	*x = QueryCalleesResponse{}
	mi := &file_indexer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCalleesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCalleesResponse) ProtoMessage() {}

func (x *QueryCalleesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCalleesResponse.ProtoReflect.Descriptor instead.
func (*QueryCalleesResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{13}
}

func (x *QueryCalleesResponse) GetCallees() []*CallInfo {
	if x != nil {
		return x.Callees
	}
	return nil
}

func (x *QueryCalleesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 搜索符号请求
type SearchSymbolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`                          // 搜索模式（支持正则表达式）
	SymbolType    string                 `protobuf:"bytes,2,opt,name=symbol_type,json=symbolType,proto3" json:"symbol_type,omitempty"`  // 符号类型（function, class, variable）
	MaxResults    int32                  `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"` // 最多返回数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSymbolRequest) Reset() {
	*x = SearchSymbolRequest{}
	mi := &file_indexer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSymbolRequest) ProtoMessage() {}

func (x *SearchSymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSymbolRequest.ProtoReflect.Descriptor instead.
func (*SearchSymbolRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{14}
}

func (x *SearchSymbolRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *SearchSymbolRequest) GetSymbolType() string {
	if x != nil {
		return x.SymbolType
	}
	return ""
}

func (x *SearchSymbolRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

// 搜索符号响应
type SearchSymbolResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SymbolId       string                 `protobuf:"bytes,1,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"`                     // 符号ID
	SymbolName     string                 `protobuf:"bytes,2,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`               // 符号名
	SymbolType     string                 `protobuf:"bytes,3,opt,name=symbol_type,json=symbolType,proto3" json:"symbol_type,omitempty"`               // 符号类型
	FilePath       string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                     // 文件路径
	LineNumber     int32                  `protobuf:"varint,5,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`              // 行号
	RelevanceScore float64                `protobuf:"fixed64,6,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"` // 相关度得分
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchSymbolResponse) Reset() {
	*x = SearchSymbolResponse{}
	mi := &file_indexer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSymbolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSymbolResponse) ProtoMessage() {}

func (x *SearchSymbolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSymbolResponse.ProtoReflect.Descriptor instead.
func (*SearchSymbolResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{15}
}

func (x *SearchSymbolResponse) GetSymbolId() string {
	if x != nil {
		return x.SymbolId
	}
	return ""
}

func (x *SearchSymbolResponse) GetSymbolName() string {
	if x != nil {
		return x.SymbolName
	}
	return ""
}

func (x *SearchSymbolResponse) GetSymbolType() string {
	if x != nil {
		return x.SymbolType
	}
	return ""
}

func (x *SearchSymbolResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SearchSymbolResponse) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *SearchSymbolResponse) GetRelevanceScore() float64 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

var File_indexer_proto protoreflect.FileDescriptor

const file_indexer_proto_rawDesc = "" +
	"\n" +
	"\rindexer.proto\x12\tcodeaudit\"\x89\x01\n" +
	"\x11BuildIndexRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x19\n" +
	"\bast_data\x18\x02 \x01(\fR\aastData\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12 \n" +
	"\vincremental\x18\x04 \x01(\bR\vincremental\"\xf1\x01\n" +
	"\x12BuildIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bindex_id\x18\x02 \x01(\tR\aindexId\x12+\n" +
	"\x11functions_indexed\x18\x03 \x01(\x05R\x10functionsIndexed\x12'\n" +
	"\x0fclasses_indexed\x18\x04 \x01(\x05R\x0eclassesIndexed\x12+\n" +
	"\x11variables_indexed\x18\x05 \x01(\x05R\x10variablesIndexed\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"y\n" +
	"\x14QueryFunctionRequest\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vexact_match\x18\x03 \x01(\bR\n" +
	"exactMatch\"\x9d\x02\n" +
	"\fFunctionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"start_line\x18\x04 \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\x05 \x01(\x05R\aendLine\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x123\n" +
	"\x15cyclomatic_complexity\x18\a \x01(\x05R\x14cyclomaticComplexity\x12\x1e\n" +
	"\n" +
	"parameters\x18\b \x03(\tR\n" +
	"parameters\x12\x1f\n" +
	"\vreturn_type\x18\t \x01(\tR\n" +
	"returnType\"o\n" +
	"\x15QueryFunctionResponse\x125\n" +
	"\tfunctions\x18\x01 \x03(\v2\x17.codeaudit.FunctionInfoR\tfunctions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"p\n" +
	"\x11QueryClassRequest\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vexact_match\x18\x03 \x01(\bR\n" +
	"exactMatch\"\x8e\x02\n" +
	"\tClassInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"start_line\x18\x04 \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\x05 \x01(\x05R\aendLine\x12\x1d\n" +
	"\n" +
	"base_class\x18\x06 \x01(\tR\tbaseClass\x12\x1e\n" +
	"\n" +
	"interfaces\x18\a \x03(\tR\n" +
	"interfaces\x12/\n" +
	"\amethods\x18\b \x03(\v2\x15.codeaudit.MethodInfoR\amethods\x12\x16\n" +
	"\x06fields\x18\t \x03(\tR\x06fields\"\x8d\x01\n" +
	"\n" +
	"MethodInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_static\x18\x03 \x01(\bR\bisStatic\x12\x1d\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bR\tisPrivate\x12\x1f\n" +
	"\vreturn_type\x18\x05 \x01(\tR\n" +
	"returnType\"e\n" +
	"\x12QueryClassResponse\x12.\n" +
	"\aclasses\x18\x01 \x03(\v2\x14.codeaudit.ClassInfoR\aclasses\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"S\n" +
	"\x13QueryCallersRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepth\"f\n" +
	"\x14QueryCallersResponse\x12-\n" +
	"\acallers\x18\x01 \x03(\v2\x13.codeaudit.CallInfoR\acallers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xc0\x01\n" +
	"\bCallInfo\x12\x1b\n" +
	"\tcaller_id\x18\x01 \x01(\tR\bcallerId\x12\x1f\n" +
	"\vcaller_name\x18\x02 \x01(\tR\n" +
	"callerName\x12\x1b\n" +
	"\tcallee_id\x18\x03 \x01(\tR\bcalleeId\x12\x1f\n" +
	"\vcallee_name\x18\x04 \x01(\tR\n" +
	"calleeName\x12\x1b\n" +
	"\tcall_line\x18\x05 \x01(\x05R\bcallLine\x12\x1b\n" +
	"\tcall_type\x18\x06 \x01(\tR\bcallType\"S\n" +
	"\x13QueryCalleesRequest\x12\x1f\n" +
	"\vfunction_id\x18\x01 \x01(\tR\n" +
	"functionId\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepth\"f\n" +
	"\x14QueryCalleesResponse\x12-\n" +
	"\acallees\x18\x01 \x03(\v2\x13.codeaudit.CallInfoR\acallees\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"q\n" +
	"\x13SearchSymbolRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x1f\n" +
	"\vsymbol_type\x18\x02 \x01(\tR\n" +
	"symbolType\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\x05R\n" +
	"maxResults\"\xdc\x01\n" +
	"\x14SearchSymbolResponse\x12\x1b\n" +
	"\tsymbol_id\x18\x01 \x01(\tR\bsymbolId\x12\x1f\n" +
	"\vsymbol_name\x18\x02 \x01(\tR\n" +
	"symbolName\x12\x1f\n" +
	"\vsymbol_type\x18\x03 \x01(\tR\n" +
	"symbolType\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vline_number\x18\x05 \x01(\x05R\n" +
	"lineNumber\x12'\n" +
	"\x0frelevance_score\x18\x06 \x01(\x01R\x0erelevanceScore2\xe8\x03\n" +
	"\aIndexer\x12I\n" +
	"\n" +
	"BuildIndex\x12\x1c.codeaudit.BuildIndexRequest\x1a\x1d.codeaudit.BuildIndexResponse\x12R\n" +
	"\rQueryFunction\x12\x1f.codeaudit.QueryFunctionRequest\x1a .codeaudit.QueryFunctionResponse\x12I\n" +
	"\n" +
	"QueryClass\x12\x1c.codeaudit.QueryClassRequest\x1a\x1d.codeaudit.QueryClassResponse\x12O\n" +
	"\fQueryCallers\x12\x1e.codeaudit.QueryCallersRequest\x1a\x1f.codeaudit.QueryCallersResponse\x12O\n" +
	"\fQueryCallees\x12\x1e.codeaudit.QueryCalleesRequest\x1a\x1f.codeaudit.QueryCalleesResponse\x12Q\n" +
	"\fSearchSymbol\x12\x1e.codeaudit.SearchSymbolRequest\x1a\x1f.codeaudit.SearchSymbolResponse0\x01B\x1e\n" +
	"\x13com.codeaudit.protoZ\a./protob\x06proto3"

var (
	file_indexer_proto_rawDescOnce sync.Once
	file_indexer_proto_rawDescData []byte
)

func file_indexer_proto_rawDescGZIP() []byte {
	file_indexer_proto_rawDescOnce.Do(func() {
		file_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)))
	})
	return file_indexer_proto_rawDescData
}

var file_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_indexer_proto_goTypes = []any{
	(*BuildIndexRequest)(nil),     // 0: codeaudit.BuildIndexRequest
	(*BuildIndexResponse)(nil),    // 1: codeaudit.BuildIndexResponse
	(*QueryFunctionRequest)(nil),  // 2: codeaudit.QueryFunctionRequest
	(*FunctionInfo)(nil),          // 3: codeaudit.FunctionInfo
	(*QueryFunctionResponse)(nil), // 4: codeaudit.QueryFunctionResponse
	(*QueryClassRequest)(nil),     // 5: codeaudit.QueryClassRequest
	(*ClassInfo)(nil),             // 6: codeaudit.ClassInfo
	(*MethodInfo)(nil),            // 7: codeaudit.MethodInfo
	(*QueryClassResponse)(nil),    // 8: codeaudit.QueryClassResponse
	(*QueryCallersRequest)(nil),   // 9: codeaudit.QueryCallersRequest
	(*QueryCallersResponse)(nil),  // 10: codeaudit.QueryCallersResponse
	(*CallInfo)(nil),              // 11: codeaudit.CallInfo
	(*QueryCalleesRequest)(nil),   // 12: codeaudit.QueryCalleesRequest
	(*QueryCalleesResponse)(nil),  // 13: codeaudit.QueryCalleesResponse
	(*SearchSymbolRequest)(nil),   // 14: codeaudit.SearchSymbolRequest
	(*SearchSymbolResponse)(nil),  // 15: codeaudit.SearchSymbolResponse
}
var file_indexer_proto_depIdxs = []int32{
	3,  // 0: codeaudit.QueryFunctionResponse.functions:type_name -> codeaudit.FunctionInfo
	7,  // 1: codeaudit.ClassInfo.methods:type_name -> codeaudit.MethodInfo
	6,  // 2: codeaudit.QueryClassResponse.classes:type_name -> codeaudit.ClassInfo
	11, // 3: codeaudit.QueryCallersResponse.callers:type_name -> codeaudit.CallInfo
	11, // 4: codeaudit.QueryCalleesResponse.callees:type_name -> codeaudit.CallInfo
	0,  // 5: codeaudit.Indexer.BuildIndex:input_type -> codeaudit.BuildIndexRequest
	2,  // 6: codeaudit.Indexer.QueryFunction:input_type -> codeaudit.QueryFunctionRequest
	5,  // 7: codeaudit.Indexer.QueryClass:input_type -> codeaudit.QueryClassRequest
	9,  // 8: codeaudit.Indexer.QueryCallers:input_type -> codeaudit.QueryCallersRequest
	12, // 9: codeaudit.Indexer.QueryCallees:input_type -> codeaudit.QueryCalleesRequest
	14, // 10: codeaudit.Indexer.SearchSymbol:input_type -> codeaudit.SearchSymbolRequest
	1,  // 11: codeaudit.Indexer.BuildIndex:output_type -> codeaudit.BuildIndexResponse
	4,  // 12: codeaudit.Indexer.QueryFunction:output_type -> codeaudit.QueryFunctionResponse
	8,  // 13: codeaudit.Indexer.QueryClass:output_type -> codeaudit.QueryClassResponse
	10, // 14: codeaudit.Indexer.QueryCallers:output_type -> codeaudit.QueryCallersResponse
	13, // 15: codeaudit.Indexer.QueryCallees:output_type -> codeaudit.QueryCalleesResponse
	15, // 16: codeaudit.Indexer.SearchSymbol:output_type -> codeaudit.SearchSymbolResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_indexer_proto_init() }
func file_indexer_proto_init() {
	if File_indexer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexer_proto_goTypes,
		DependencyIndexes: file_indexer_proto_depIdxs,
		MessageInfos:      file_indexer_proto_msgTypes,
	}.Build()
	File_indexer_proto = out.File
	file_indexer_proto_goTypes = nil
	file_indexer_proto_depIdxs = nil
}
